name: CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 7 * * *" # every day at 07:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build and run
        run: |
          docker build --tag alejgarciarodriguez/atom-feed:latest --target=app .
          docker run --volume=${{ github.workspace }}/feed:/var/app/feed alejgarciarodriguez/atom-feed:latest
          git checkout -B feed
          git add feed/atom.xml
          git config --global user.email "alejgarciarodriguez@gmail.com"
          git config --global user.name "alejgarciarodriguez"
          git commit -m "update feed"
          git push origin feed